-- Shiksha-AI: Detailed Postgres Schema (Supabase)
-- Focus: users, AI tutor signals, planner, streaks, weak-topic detection
-- Paste into Supabase SQL editor. Requires pgcrypto for gen_random_uuid().
create extension if not exists "pgcrypto";

-- =========================
-- ENUMS
-- =========================
create type difficulty_enum as enum ('easy','medium','hard');
create type role_enum as enum ('user','assistant');
create type activity_enum as enum ('chat','quiz_attempt','plan_completed','task_completed','login');

-- =========================
-- CORE USER TABLES
-- =========================
create table users (
  id uuid primary key default gen_random_uuid(),
  email text unique,
  name text,
  created_at timestamptz default now()
);

create table user_profile (
  user_id uuid primary key references users(id) on delete cascade,
  class int not null check (class between 6 and 12),
  board text default 'CBSE',
  subjects text[] not null,                -- e.g. {'Maths','Science'}
  weak_topics text[] default '{}',         -- quick storage (human-readable) but we also compute structured weakness
  strong_topics text[] default '{}',
  target_exams text[] default '{}',        -- e.g. {'Boards','JEE'}
  daily_study_hours int default 1,
  timezone text default 'Asia/Kolkata',
  updated_at timestamptz default now()
);

-- =========================
-- NCERT / TOPIC MASTER
-- Canonical mapping of curriculum -> used by Tutor & Planner
-- =========================
create table topic_master (
  id uuid primary key default gen_random_uuid(),
  curriculum_class int not null check (curriculum_class between 6 and 12),
  board text not null default 'CBSE',
  subject text not null,                  -- e.g. 'Science'
  chapter text not null,                  -- e.g. 'Motion'
  chapter_order int default 0,
  topic text not null,                    -- more granular topic e.g. 'Newton's First Law'
  topic_order int default 0,
  source_file text,                        -- pointer to NCERT PDF path / filename
  source_page_range text,                  -- e.g. '12-18'
  created_at timestamptz default now(),
  unique(curriculum_class, board, subject, chapter, topic)
);

-- Optionally store chunk metadata for RAG (no vectors in PG)
create table ncert_chunks (
  id uuid primary key default gen_random_uuid(),
  topic_master_id uuid references topic_master(id) on delete set null,
  chunk_text text not null,
  token_count int,
  chunk_order int default 0,
  source text,                 -- original pdf page / filename
  external_vector_id text,     -- external vector DB ID if you use one
  created_at timestamptz default now()
);

-- =========================
-- TUTOR CHAT: sessions + messages
-- (store detected subject/topic info per message for signal extraction)
-- =========================
create table tutor_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  started_at timestamptz default now(),
  last_active_at timestamptz default now()
);

create table tutor_messages (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references tutor_sessions(id) on delete cascade,
  user_id uuid references users(id) on delete cascade,
  role role_enum not null,
  content text not null,
  detected_class int,           -- optional: class from detection pipeline (6..12)
  detected_subject text,        -- e.g. 'Science'
  detected_chapter text,        -- e.g. 'Motion'
  detected_topic text,          -- e.g. 'Newton First Law'
  detection_confidence numeric, -- 0..1 how confident the detector/LLM is
  answer_mode text,             -- 'simple','2-mark','5-mark','topper' for assistant messages
  created_at timestamptz default now()
);

-- Indexes to speed queries by topic and date
create index on tutor_messages (user_id);
create index on tutor_messages (detected_topic);
create index on tutor_messages (created_at);

-- =========================
-- QUIZZES + ATTEMPTS (planner signals)
-- =========================
create table quizzes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  created_by text,               -- system / teacher / autogenerated
  subject text not null,
  topic text not null,
  chapter text,
  difficulty difficulty_enum default 'medium',
  total_questions int not null check (total_questions > 0),
  config jsonb default '{}' ,    -- store question prefs, e.g. {"num_mcq": 5}
  created_at timestamptz default now()
);

create table quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  quiz_id uuid references quizzes(id) on delete cascade,
  user_id uuid references users(id) on delete cascade,
  correct_answers int not null check (correct_answers >= 0),
  total_questions int not null check (total_questions > 0),
  time_taken_seconds int default 0,
  score_percent numeric generated always as ( (correct_answers::numeric / total_questions::numeric) * 100 ) stored,
  attempt_meta jsonb default '{}', -- store per-question stats if needed
  created_at timestamptz default now()
);

create index on quiz_attempts (user_id);
create index on quiz_attempts (created_at);

-- =========================
-- STUDY PLANS + PLAN TASKS (planner output + per-task status)
-- =========================
create table study_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  plan_date date not null,               -- the date this plan is for
  generated_by text default 'system',    -- 'system' or 'teacher'
  plan_meta jsonb default '{}',          -- high-level metadata
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_id, plan_date)
);

-- plan tasks are individual items in a day's plan
create table plan_tasks (
  id uuid primary key default gen_random_uuid(),
  study_plan_id uuid references study_plans(id) on delete cascade,
  user_id uuid references users(id) on delete cascade,
  task_type text not null,               -- 'study','quiz','revision','watch_video'
  subject text,
  chapter text,
  topic text,
  duration_min int default 0,
  quiz_id uuid references quizzes(id) on delete set null,
  scheduled_at timestamptz,              -- scheduled time in user's timezone
  status text default 'pending',         -- 'pending','in_progress','completed','skipped'
  completed_at timestamptz,
  created_at timestamptz default now()
);

create index on plan_tasks (user_id);
create index on plan_tasks (study_plan_id);

-- =========================
-- STUDY ACTIVITY (user behavior)
-- each row = a user action (chat, quiz_attempt, plan_task completed, etc.)
-- =========================
create table study_activity (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  activity_type activity_enum not null,
  subject text,
  chapter text,
  topic text,
  extra jsonb default '{}',  -- e.g. {"quiz_attempt_id": "..."}
  created_at timestamptz default now()
);

create index on study_activity (user_id, created_at);

-- =========================
-- AGGREGATES & WEAKNESS SCORES
-- computed periodically (batch job) or on-demand via function
-- stores user's weakness score at subject/topic/chapter granularity
-- =========================
create table user_topic_stats (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  topic_master_id uuid references topic_master(id) on delete set null,
  class int,                     -- redundant but handy
  subject text,
  chapter text,
  topic text,
  questions_asked int default 0, -- count of tutor questions from user about this topic
  quizzes_taken int default 0,
  avg_quiz_score numeric default 0, -- 0..100
  last_seen_at timestamptz,
  updated_at timestamptz default now(),
  unique (user_id, topic_master_id)
);

-- This table stores computed weakness (0=strong -> 100=weak)
create table user_topic_weakness (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  topic_master_id uuid references topic_master(id) on delete set null,
  subject text,
  chapter text,
  topic text,
  weakness_score numeric not null check (weakness_score >= 0 and weakness_score <= 100),
  evidence_count int default 0,    -- how many signals contributed
  last_computed_at timestamptz default now(),
  note text,
  unique (user_id, topic_master_id)
);

create index on user_topic_weakness (user_id, weakness_score desc);

-- =========================
-- STREAKS: optional table to store precomputed streaks
-- You can also compute on the fly, but storing avoids heavy queries during demo
-- =========================
create table user_streaks (
  user_id uuid primary key references users(id) on delete cascade,
  current_streak_days int default 0,
  longest_streak_days int default 0,
  last_activity_date date,
  updated_at timestamptz default now()
);

-- =========================
-- INDEXES for performance
-- =========================
create index on topic_master (curriculum_class, subject, chapter, topic);
create index on ncert_chunks (topic_master_id);
create index on quizzes (user_id);
create index on study_plans (user_id, plan_date);

-- =========================
-- HELPER FUNCTIONS
-- - compute_user_streak(user_uuid)
-- - recompute_user_topic_weakness(user_uuid)
-- These are basic; tweak weights and logic as needed.
-- =========================

/*
 compute_user_streak:
  - counts consecutive days up to current_date where study_activity exists for the user
  - returns integer days in current streak
*/
create or replace function compute_user_streak(p_user_id uuid)
returns int language plpgsql as $$
declare
  cur_date date := current_date;
  streak int := 0;
  d date;
begin
  -- loop backwards from today until a missing day
  d := cur_date;
  loop
    if exists (
      select 1 from study_activity
      where user_id = p_user_id
        and created_at::date = d
    ) then
      streak := streak + 1;
      d := d - interval '1 day';
    else
      exit;
    end if;
  end loop;

  -- update user_streaks table (upsert)
  insert into user_streaks (user_id, current_streak_days, last_activity_date, updated_at)
  values (p_user_id, streak, current_date, now())
  on conflict (user_id) do update
    set current_streak_days = excluded.current_streak_days,
        last_activity_date = excluded.last_activity_date,
        updated_at = now();

  return streak;
end;
$$;

-- Example: select compute_user_streak('some-uuid');


/*
 recompute_user_topic_weakness:
  - aggregates quiz performance + tutor questions for user per topic_master
  - formula (example, tweak weights as you want):
      weakness_score = clamp( 0.7*(100 - avg_quiz_score) + 0.3*min(100, questions_asked * 10), 0, 100)
  - stores upsert into user_topic_weakness
*/
create or replace function recompute_user_topic_weakness(p_user_id uuid)
returns void language plpgsql as $$
declare
  rec record;
  v_weakness_score numeric;
  v_evidence_count int;
begin
  -- Aggregate quiz data per topic (subject, chapter, topic) using quizzes & quiz_attempts
  for rec in
    select
      tm.id as topic_master_id,
      coalesce(tm.curriculum_class, 0) as class,
      tm.subject,
      tm.chapter,
      tm.topic,
      coalesce(qs.quizzes_taken,0) as quizzes_taken,
      coalesce(qs.avg_quiz_score,0) as avg_quiz_score,
      coalesce(tm_qa.questions_asked,0) as questions_asked
    from topic_master tm
    left join (
      select q.topic, q.chapter, q.subject, count(distinct q.id) as quizzes_taken,
             avg(qa.score_percent) as avg_quiz_score
      from quizzes q
      join quiz_attempts qa on qa.quiz_id = q.id
      where q.user_id = p_user_id
      group by q.subject, q.chapter, q.topic
    ) qs on qs.topic = tm.topic and qs.chapter = tm.chapter and qs.subject = tm.subject
    left join (
      select tm2.topic, tm2.chapter, tm2.subject, count(*) as questions_asked
      from tutor_messages tm2msgs
      join topic_master tm2 on (tm2.topic = tm2msgs.detected_topic and tm2.chapter = tm2msgs.detected_chapter and tm2.subject = tm2msgs.detected_subject)
      where tm2msgs.user_id = p_user_id
      group by tm2.topic, tm2.chapter, tm2.subject
    ) tm_qa on tm_qa.topic = tm.topic and tm_qa.chapter = tm.chapter and tm_qa.subject = tm.subject
    where tm.subject is not null
  loop
    -- compute weakness score
    -- If no quizzes, avg_quiz_score will be 0; questions_asked will influence score
    -- weights: quiz component 0.7, question component 0.3
    -- question impact capped at 100 (e.g. >10 questions saturates)
    v_weakness_score := greatest(0, least(100,
      (0.7 * (100 - coalesce(rec.avg_quiz_score,0))) + (0.3 * least(100, (coalesce(rec.questions_asked,0) * 10)))
    ));
    
    v_evidence_count := coalesce(rec.quizzes_taken,0) + coalesce(rec.questions_asked,0);
    
    insert into user_topic_weakness (user_id, topic_master_id, subject, chapter, topic, weakness_score, evidence_count, last_computed_at)
    values (
      p_user_id,
      rec.topic_master_id,
      rec.subject,
      rec.chapter,
      rec.topic,
      v_weakness_score,
      v_evidence_count,
      now()
    )
    on conflict (user_id, topic_master_id) do update
    set weakness_score = excluded.weakness_score,
        evidence_count = excluded.evidence_count,
        last_computed_at = excluded.last_computed_at;
  end loop;
end;
$$;